### ISSUE TITLE
Unexpected token N in JSON at position 0

### ISSUE THREAD

**Issue by kytwb** [getferdi/server#17]
Not sure what changed in the way we handle announcements, but when there is no announcement for a version, the API returns:

> No announcement found.

E.g. https://api.getferdi.com/v1/announcements/5.4.1-beta.2

And cause in the client:

> Unexpected token N in JSON at position 0

Via https://sentry.io/share/issue/169d396e342048dcb3f47bcc396b32b9/.
I think we should return an empty object if there is no announcement (from reading the client code handling the request).

**Comment by vantezzen** [comment]
Hmm, I've just copied what Franz's API is returning: <http://api.franzinfra.com/v1/announcements/0.0.0>. I think the issue is that the Ferdi API isn't actually returning a 404 but a 200 on that route:
https://github.com/getferdi/server/blob/cc8471e39664c7864cdbac6e3234220652602c9d/app/Controllers/Http/StaticController.js#L237
I think that should fix the problem?

**Comment by kytwb** [comment]
Good catch, pushing a fix!
